from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from datetime import datetime
import uuid

class ScriptSource(str, Enum):
    UPLOAD = "upload"
    AD_SCRIPT_LAB = "ad_script_lab"

class ScriptInput(BaseModel):
    source: ScriptSource
    content: Optional[str] = None  # Text content
    ad_script_run_id: Optional[str] = None  # Link to Ad Script Lab run
    file_name: Optional[str] = None # For uploads

class Character(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    name: str
    description: str
    visual_prompt: str
    image_url: Optional[str] = None  # Generated by Nano Banana Pro

class ClarificationOption(BaseModel):
    id: str
    text: str

class AssetType(str, Enum):
    LOGO = "logo"
    PRODUCT = "product"
    BRAND_GUIDE = "brand_guide"
    CHARACTER_REF = "character_ref"
    LOCATION_REF = "location_ref"
    OTHER = "other"

class AssetRequest(BaseModel):
    """Request for user to upload an asset needed for the storyboard."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    asset_type: AssetType
    name: str  # e.g., "Company Logo", "Product Shot"
    description: str  # Why we need it and how it will be used
    required: bool = True
    uploaded_url: Optional[str] = None  # Filled after user uploads

class ClarificationQuestion(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    question: str
    context: str  # Why we are asking
    options: List[ClarificationOption]
    selected_option_id: Optional[str] = None
    custom_answer: Optional[str] = None

class VisualPromptMetadata(BaseModel):
    """Structured visual prompt with components for AI image generation."""
    subject: str                                    # Main subject/action description
    style: List[str] = []                           # ["cinematic", "photorealistic", "commercial"]
    lighting: Optional[str] = None                  # "soft natural light, golden hour"
    composition: Optional[str] = None               # "rule of thirds, shallow depth of field"
    color_palette: Optional[str] = None             # "warm tones, muted pastels"
    camera: Optional[str] = None                    # "35mm lens, eye level"
    quality: List[str] = []                         # ["8K", "high detail", "sharp focus"]
    negative: Optional[str] = None                  # "blurry, watermark, text, distorted"
    aspect_ratio: str = "16:9"


class VideoPromptMetadata(BaseModel):
    """Video-specific prompt metadata for AI video generators."""
    subject: str                                    # Main action/motion description
    motion: Optional[str] = None                    # "character walks slowly toward camera"
    camera_movement: Optional[str] = None           # "slow dolly in", "static", "pan left"
    duration_seconds: float = 4.0                   # Suggested clip duration
    pacing: Optional[str] = None                    # "slow", "medium", "fast"
    transition_out: Optional[str] = None            # "cut", "fade", "dissolve"
    audio_sync: Optional[str] = None                # "beat drop at end"


class StoryboardScene(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    scene_number: int
    description: str
    action: str
    characters_present: List[str]  # List of Character IDs
    setting: str
    camera_angle: Optional[str] = None
    visual_prompt: str  # Legacy field for backward compatibility
    image_url: Optional[str] = None

    # Production Fields
    duration_seconds: Optional[float] = None
    start_timecode: Optional[str] = None            # "00:00:05"
    end_timecode: Optional[str] = None              # "00:00:09"

    # Dialogue & Audio
    dialogue: Optional[str] = None                  # On-screen spoken lines
    voiceover: Optional[str] = None                 # VO text
    sound_notes: Optional[str] = None               # "upbeat music, door SFX"

    # Shot Classification
    shot_type: Optional[str] = None                 # "wide", "medium", "close_up", "establishing"
    transition_in: Optional[str] = "cut"
    transition_out: Optional[str] = "cut"

    # Narrative
    emotional_beat: Optional[str] = None            # "tension", "relief", "climax"

    # Enhanced Prompts
    image_prompt: Optional[VisualPromptMetadata] = None
    video_prompt: Optional[VideoPromptMetadata] = None

class Storyboard(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str
    characters: List[Character]
    scenes: List[StoryboardScene]
    created_at: datetime = Field(default_factory=datetime.utcnow)

    # Production Metadata
    total_duration_seconds: Optional[float] = None
    narrative_summary: Optional[str] = None
    emotional_arc: Optional[str] = None             # "curiosity -> engagement -> satisfaction"
    key_message: Optional[str] = None

class AnalysisResult(BaseModel):
    analysis_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    script_summary: str
    detected_characters: List[Character]
    clarification_questions: List[ClarificationQuestion]
    asset_requests: List[AssetRequest] = []  # Assets needed for the storyboard
    status: str = "pending_clarification" # pending_clarification, ready_to_generate

class UploadedAsset(BaseModel):
    """An asset that was uploaded by the user."""
    asset_request_id: str  # Links back to the AssetRequest
    file_url: str  # URL/path where the file is stored
    file_name: str
    mime_type: Optional[str] = None

class ClarificationResponse(BaseModel):
    analysis_id: str
    answers: Dict[str, str]  # question_id -> option_id or custom text
    uploaded_assets: List[UploadedAsset] = []  # Assets uploaded by user

class StoryboardJobStatus(str, Enum):
    PENDING = "pending"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"

class StoryboardJob(BaseModel):
    job_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    analysis_id: str
    status: StoryboardJobStatus
    storyboard: Optional[Storyboard] = None
    error: Optional[str] = None
    progress: int = 0
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

