#!/usr/bin/env pwsh
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Defaults (minor units)
$BASIC_USD   = ${env:BASIC_USD}   | ForEach-Object { if ($_ -and $_ -match '^[0-9]+$') { [int]$_ } else { 999 } }
$BASIC_GBP   = ${env:BASIC_GBP}   | ForEach-Object { if ($_ -and $_ -match '^[0-9]+$') { [int]$_ } else { 899 } }
$BASIC_EUR   = ${env:BASIC_EUR}   | ForEach-Object { if ($_ -and $_ -match '^[0-9]+$') { [int]$_ } else { 949 } }
$FEATURED_USD= ${env:FEATURED_USD}| ForEach-Object { if ($_ -and $_ -match '^[0-9]+$') { [int]$_ } else { 1999 } }
$FEATURED_GBP= ${env:FEATURED_GBP}| ForEach-Object { if ($_ -and $_ -match '^[0-9]+$') { [int]$_ } else { 1799 } }
$FEATURED_EUR= ${env:FEATURED_EUR}| ForEach-Object { if ($_ -and $_ -match '^[0-9]+$') { [int]$_ } else { 1899 } }
$PREMIUM_USD = ${env:PREMIUM_USD} | ForEach-Object { if ($_ -and $_ -match '^[0-9]+$') { [int]$_ } else { 2999 } }
$PREMIUM_GBP = ${env:PREMIUM_GBP} | ForEach-Object { if ($_ -and $_ -match '^[0-9]+$') { [int]$_ } else { 2799 } }
$PREMIUM_EUR = ${env:PREMIUM_EUR} | ForEach-Object { if ($_ -and $_ -match '^[0-9]+$') { [int]$_ } else { 2899 } }

$Stripe = 'C:\stripe.exe'
if (-not (Test-Path $Stripe)) { throw 'Stripe CLI not found at C:\stripe.exe' }

function Invoke-Stripe {
  param([Parameter(ValueFromRemainingArguments=$true)][string[]]$Args)
  & $Stripe --live --color off @Args
}

function Ensure-Product {
  param([string]$Name)
  $json = Invoke-Stripe products list --limit 100
  $parsed = $json | ConvertFrom-Json
  $id = ($parsed.data | Where-Object { $_.name -eq $Name } | Select-Object -First 1).id
  if (-not $id) {
    $created = Invoke-Stripe products create --name $Name | ConvertFrom-Json
    $id = $created.id
  }
  return $id
}

function Ensure-Price {
  param([string]$ProductId, [string]$Currency, [int]$Amount, [string]$Lookup)
  $json = Invoke-Stripe prices list --product $ProductId --limit 100
  $parsed = $json | ConvertFrom-Json
  $match = $parsed.data | Where-Object { $_.currency -eq $Currency -and $_.unit_amount -eq $Amount -and $_.recurring.interval -eq 'month' -and $_.active -eq $true } | Select-Object -First 1
  if ($match) { return $match.id }
  $created = Invoke-Stripe prices create --product $ProductId --currency $Currency --unit-amount $Amount --recurring.interval month --lookup-key $Lookup --nickname $Lookup | ConvertFrom-Json
  return $created.id
}

$basicId    = Ensure-Product 'Vendor Subscription Basic'
$featuredId = Ensure-Product 'Vendor Subscription Featured'
$premiumId  = Ensure-Product 'Vendor Subscription Premium'

$P_BASIC_USD = Ensure-Price $basicId 'usd' $BASIC_USD 'basic_monthly_usd'
$P_BASIC_GBP = Ensure-Price $basicId 'gbp' $BASIC_GBP 'basic_monthly_gbp'
$P_BASIC_EUR = Ensure-Price $basicId 'eur' $BASIC_EUR 'basic_monthly_eur'

$P_FEAT_USD = Ensure-Price $featuredId 'usd' $FEATURED_USD 'featured_monthly_usd'
$P_FEAT_GBP = Ensure-Price $featuredId 'gbp' $FEATURED_GBP 'featured_monthly_gbp'
$P_FEAT_EUR = Ensure-Price $featuredId 'eur' $FEATURED_EUR 'featured_monthly_eur'

$P_PREM_USD = Ensure-Price $premiumId 'usd' $PREMIUM_USD 'premium_monthly_usd'
$P_PREM_GBP = Ensure-Price $premiumId 'gbp' $PREMIUM_GBP 'premium_monthly_gbp'
$P_PREM_EUR = Ensure-Price $premiumId 'eur' $PREMIUM_EUR 'premium_monthly_eur'

$envOut = '.env.stripe-prices'
@(
  '# Generated by LIVE bootstrap',
  "STRIPE_PRICE_BASIC_USD=$P_BASIC_USD",
  "STRIPE_PRICE_FEATURED_USD=$P_FEAT_USD",
  "STRIPE_PRICE_PREMIUM_USD=$P_PREM_USD",
  "STRIPE_PRICE_BASIC_GBP=$P_BASIC_GBP",
  "STRIPE_PRICE_FEATURED_GBP=$P_FEAT_GBP",
  "STRIPE_PRICE_PREMIUM_GBP=$P_PREM_GBP",
  "STRIPE_PRICE_BASIC_EUR=$P_BASIC_EUR",
  "STRIPE_PRICE_FEATURED_EUR=$P_FEAT_EUR",
  "STRIPE_PRICE_PREMIUM_EUR=$P_PREM_EUR"
) | Set-Content -Path $envOut -NoNewline:$false

Write-Host "Wrote $envOut (LIVE)"
