#!/usr/bin/env pwsh
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$BASIC_USD=999; $BASIC_GBP=899; $BASIC_EUR=949
$FEATURED_USD=1999; $FEATURED_GBP=1799; $FEATURED_EUR=1899
$PREMIUM_USD=2999; $PREMIUM_GBP=2799; $PREMIUM_EUR=2899

$Stripe = 'C:\stripe.exe'
function S { param([Parameter(ValueFromRemainingArguments=$true)][string[]]$Args) & $Stripe --live --color off @Args }

$basic    = S products create --name 'Vendor Subscription Basic'    | ConvertFrom-Json
$featured = S products create --name 'Vendor Subscription Featured' | ConvertFrom-Json
$premium  = S products create --name 'Vendor Subscription Premium'  | ConvertFrom-Json

$pb_usd = S prices create --product $basic.id    --currency usd --unit-amount $BASIC_USD    --recurring.interval month --lookup-key basic_monthly_usd    --nickname basic_monthly_usd    | ConvertFrom-Json
$pb_gbp = S prices create --product $basic.id    --currency gbp --unit-amount $BASIC_GBP    --recurring.interval month --lookup-key basic_monthly_gbp    --nickname basic_monthly_gbp    | ConvertFrom-Json
$pb_eur = S prices create --product $basic.id    --currency eur --unit-amount $BASIC_EUR    --recurring.interval month --lookup-key basic_monthly_eur    --nickname basic_monthly_eur    | ConvertFrom-Json

$pf_usd = S prices create --product $featured.id --currency usd --unit-amount $FEATURED_USD --recurring.interval month --lookup-key featured_monthly_usd --nickname featured_monthly_usd | ConvertFrom-Json
$pf_gbp = S prices create --product $featured.id --currency gbp --unit-amount $FEATURED_GBP --recurring.interval month --lookup-key featured_monthly_gbp --nickname featured_monthly_gbp | ConvertFrom-Json
$pf_eur = S prices create --product $featured.id --currency eur --unit-amount $FEATURED_EUR --recurring.interval month --lookup-key featured_monthly_eur --nickname featured_monthly_eur | ConvertFrom-Json

$pp_usd = S prices create --product $premium.id  --currency usd --unit-amount $PREMIUM_USD  --recurring.interval month --lookup-key premium_monthly_usd  --nickname premium_monthly_usd  | ConvertFrom-Json
$pp_gbp = S prices create --product $premium.id  --currency gbp --unit-amount $PREMIUM_GBP  --recurring.interval month --lookup-key premium_monthly_gbp  --nickname premium_monthly_gbp  | ConvertFrom-Json
$pp_eur = S prices create --product $premium.id  --currency eur --unit-amount $PREMIUM_EUR  --recurring.interval month --lookup-key premium_monthly_eur  --nickname premium_monthly_eur  | ConvertFrom-Json

$envOut = '.env.stripe-prices'
@(
  '# Generated by LIVE direct create',
  "STRIPE_PRICE_BASIC_USD=$($pb_usd.id)",
  "STRIPE_PRICE_FEATURED_USD=$($pf_usd.id)",
  "STRIPE_PRICE_PREMIUM_USD=$($pp_usd.id)",
  "STRIPE_PRICE_BASIC_GBP=$($pb_gbp.id)",
  "STRIPE_PRICE_FEATURED_GBP=$($pf_gbp.id)",
  "STRIPE_PRICE_PREMIUM_GBP=$($pp_gbp.id)",
  "STRIPE_PRICE_BASIC_EUR=$($pb_eur.id)",
  "STRIPE_PRICE_FEATURED_EUR=$($pf_eur.id)",
  "STRIPE_PRICE_PREMIUM_EUR=$($pp_eur.id)"
) | Set-Content -Path $envOut -NoNewline:$false

Write-Host 'Wrote .env.stripe-prices (LIVE)'
