#!/usr/bin/env pwsh
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$BASIC='prod_SsXYuqxZ9uA2A9'
$FEATURED='prod_SsXYQALhOmVZmB'
$PREMIUM='prod_SsXZnjSyD0zqq5'

$BASIC_USD=999; $BASIC_GBP=899; $BASIC_EUR=949
$FEATURED_USD=1999; $FEATURED_GBP=1799; $FEATURED_EUR=1899
$PREMIUM_USD=2999; $PREMIUM_GBP=2799; $PREMIUM_EUR=2899

$Stripe = 'C:\stripe.exe'
if (-not (Test-Path $Stripe)) { throw 'Stripe CLI not found at C:\stripe.exe' }

function Ensure-Price {
  param([string]$Product,[string]$Currency,[int]$Amount,[string]$Lookup)
  $query = "product:'$Product' AND currency:'$Currency' AND recurring.interval:'month' AND lookup_key:'$Lookup' AND active:'true'"
  $searchOut = & $Stripe prices search --live --color off --query $query
  $m = [regex]::Match($searchOut, '"id"\s*:\s*"(price_[^"]+)' )
  if ($m.Success) { return $m.Groups[1].Value }
  $createOut = & $Stripe prices create --live --color off --product $Product --currency $Currency --unit-amount $Amount --recurring.interval month --lookup-key $Lookup --nickname $Lookup
  $m2 = [regex]::Match($createOut, '"id"\s*:\s*"(price_[^"]+)' )
  if ($m2.Success) { return $m2.Groups[1].Value }
  throw "Failed to ensure price for $Product $Currency $Lookup"
}

$pb_usd = Ensure-Price $BASIC 'usd' $BASIC_USD 'basic_monthly_usd'
$pb_gbp = Ensure-Price $BASIC 'gbp' $BASIC_GBP 'basic_monthly_gbp'
$pb_eur = Ensure-Price $BASIC 'eur' $BASIC_EUR 'basic_monthly_eur'

$pf_usd = Ensure-Price $FEATURED 'usd' $FEATURED_USD 'featured_monthly_usd'
$pf_gbp = Ensure-Price $FEATURED 'gbp' $FEATURED_GBP 'featured_monthly_gbp'
$pf_eur = Ensure-Price $FEATURED 'eur' $FEATURED_EUR 'featured_monthly_eur'

$pp_usd = Ensure-Price $PREMIUM 'usd' $PREMIUM_USD 'premium_monthly_usd'
$pp_gbp = Ensure-Price $PREMIUM 'gbp' $PREMIUM_GBP 'premium_monthly_gbp'
$pp_eur = Ensure-Price $PREMIUM 'eur' $PREMIUM_EUR 'premium_monthly_eur'

$envOut = '.env.stripe-prices'
@(
  '# Generated by LIVE ensure (regex parse)',
  "STRIPE_PRICE_BASIC_USD=$pb_usd",
  "STRIPE_PRICE_FEATURED_USD=$pf_usd",
  "STRIPE_PRICE_PREMIUM_USD=$pp_usd",
  "STRIPE_PRICE_BASIC_GBP=$pb_gbp",
  "STRIPE_PRICE_FEATURED_GBP=$pf_gbp",
  "STRIPE_PRICE_PREMIUM_GBP=$pp_gbp",
  "STRIPE_PRICE_BASIC_EUR=$pb_eur",
  "STRIPE_PRICE_FEATURED_EUR=$pf_eur",
  "STRIPE_PRICE_PREMIUM_EUR=$pp_eur"
) | Set-Content -Path $envOut -NoNewline:$false

Write-Host "Wrote $envOut (LIVE)"
