#!/usr/bin/env pwsh
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# Product IDs provided
$BASIC='prod_SsXYuqxZ9uA2A9'
$FEATURED='prod_SsXYQALhOmVZmB'
$PREMIUM='prod_SsXZnjSyD0zqq5'

# Pricing (minor units)
$BASIC_USD=999; $BASIC_GBP=899; $BASIC_EUR=949
$FEATURED_USD=1999; $FEATURED_GBP=1799; $FEATURED_EUR=1899
$PREMIUM_USD=2999; $PREMIUM_GBP=2799; $PREMIUM_EUR=2899

# Live secret key (read from environment at runtime)
$liveKey = $env:STRIPE_SECRET_KEY

function Create-Price {
  param([string]$Product,[string]$Currency,[int]$Amount,[string]$Lookup)
  $headers = @{ 'Authorization' = "Bearer $liveKey"; 'Content-Type' = 'application/x-www-form-urlencoded' }
  $body = "product=$Product&currency=$Currency&unit_amount=$Amount&recurring[interval]=month&lookup_key=$Lookup&nickname=$Lookup"
  try {
    $response = Invoke-RestMethod -Uri 'https://api.stripe.com/v1/prices' -Method Post -Headers $headers -Body $body
    return $response.id
  } catch {
    Write-Host "Failed to create price for $Product $Currency $Lookup : $($_.Exception.Message)"
    return $null
  }
}

$pb_usd = Create-Price $BASIC 'usd' $BASIC_USD 'basic_monthly_usd'
$pb_gbp = Create-Price $BASIC 'gbp' $BASIC_GBP 'basic_monthly_gbp'
$pb_eur = Create-Price $BASIC 'eur' $BASIC_EUR 'basic_monthly_eur'

$pf_usd = Create-Price $FEATURED 'usd' $FEATURED_USD 'featured_monthly_usd'
$pf_gbp = Create-Price $FEATURED 'gbp' $FEATURED_GBP 'featured_monthly_gbp'
$pf_eur = Create-Price $FEATURED 'eur' $FEATURED_EUR 'featured_monthly_eur'

$pp_usd = Create-Price $PREMIUM 'usd' $PREMIUM_USD 'premium_monthly_usd'
$pp_gbp = Create-Price $PREMIUM 'gbp' $PREMIUM_GBP 'premium_monthly_gbp'
$pp_eur = Create-Price $PREMIUM 'eur' $PREMIUM_EUR 'premium_monthly_eur'

$envOut = '.env.stripe-prices'
@(
  '# Generated by LIVE API direct calls',
  "STRIPE_PRICE_BASIC_USD=$pb_usd",
  "STRIPE_PRICE_FEATURED_USD=$pf_usd",
  "STRIPE_PRICE_PREMIUM_USD=$pp_usd",
  "STRIPE_PRICE_BASIC_GBP=$pb_gbp",
  "STRIPE_PRICE_FEATURED_GBP=$pf_gbp",
  "STRIPE_PRICE_PREMIUM_GBP=$pp_gbp",
  "STRIPE_PRICE_BASIC_EUR=$pb_eur",
  "STRIPE_PRICE_FEATURED_EUR=$pf_eur",
  "STRIPE_PRICE_PREMIUM_EUR=$pp_eur"
) | Set-Content -Path $envOut -NoNewline:$false

Write-Host "Wrote $envOut (LIVE API)"
